"""record summary

Revision ID: 0f7837625a0c
Revises: 0001
Create Date: 2026-10-05 00:12:04.294879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0f7837625a0c"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
