"""assets and amortization entries

Revision ID: 919fc9b84165
Revises: d5b4a3ad43e6
Create Date: 2026-10-06 02:13:18.803875

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "919fc9b84165"
down_revision: str | None = "d5b4a3ad43e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("acquisition_date", sa.String(length=10), nullable=False),
        sa.Column("cost", sa.String(length=20), nullable=False),
        sa.Column("annual_rate", sa.String(length=10), nullable=False),
        sa.Column("residual_value", sa.String(length=20), nullable=False),
        sa.Column("quipu_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("quipu_ref", name=op.f("uq_assets_quipu_ref")),
    )
    op.create_table(
        "amortization_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.String(length=20), nullable=False),
        sa.Column("holded_entry_id", sa.String(length=100), nullable=True),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_amortization_entries_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amortization_entries")),
        sa.UniqueConstraint(
            "asset_id", "number", name=op.f("uq_amortization_entries_asset_id_number")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amortization_entries")
    op.drop_table("assets")
    # ### end Alembic commands ###
