"""record overrides

Revision ID: d5b4a3ad43e6
Revises: 0f7837625a0c
Create Date: 2026-10-05 01:35:47.633973

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d5b4a3ad43e6"
down_revision: str | None = "0f7837625a0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("overrides", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.drop_column("overrides")

    # ### end Alembic commands ###
